# Generated by Django 3.2.8 on 2021-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='jobs',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
