# Generated by Django 3.2.8 on 2021-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_settings_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.SlugField(max_length=255)),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatar/'),
            preserve_default=False,
        ),
    ]
