# Generated by Django 3.2.8 on 2021-10-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211027_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=255)),
                ('birth_day', models.DateField()),
                ('web_site', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('text', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
