# Generated by Django 3.2.8 on 2021-10-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211027_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='img',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
    ]
