# Generated by Django 3.2.8 on 2021-10-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experience_experiencetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.experiencetype'),
            preserve_default=False,
        ),
    ]
