# Generated by Django 3.2.8 on 2021-10-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experience_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='resume',
            field=models.FileField(default=1, upload_to='resume/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='main.experiencetype'),
        ),
    ]
