# Generated by Django 3.2.8 on 2021-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211027_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='city',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='web_site',
        ),
    ]
