# Generated by Django 3.2.8 on 2021-10-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_projecttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='experiencetype',
            name='empty',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
