# Generated by Django 3.2.8 on 2021-10-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211028_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
