# Generated by Django 3.2.8 on 2021-10-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sociallink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='social_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
