# Generated by Django 3.2.8 on 2021-11-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='more',
            field=models.ManyToManyField(to='main.AboutMeMore'),
        ),
    ]
